### ISSUE TITLE
Trello Token - App not found

### ISSUE THREAD

**Issue by markusTriesIt** [danslimmon/oscar#43]
Hi there,

Trying to set up Oscar but cant't create a token on trello since the URL doesn't work:

https://trello.com/1/authorize?key={0}&name=oscar&expiration=never&response_type=token&scope=read,write

Always returns "App not found" for me, even if I am logged in prior to the trying.

Anybody has a clue?

**Comment by danslimmon** [comment]
The `{0}` in that URL looks suspicious to me. Is that just shorthand, or are you really not replacing that with your app key as the script does?

**Comment by markusTriesIt** [comment]
I see, sorry for this stupid mistake. I just went through the install file to make all accounts I need before I actually run it on my Raspberry Pi - Stupid idea I guess.

The link will be altered when executing the install.py file on raspian, correct? {0} is only a wildcard?

Line 47 (trello_app_key = '95be613d21fcfa29f3580cc3ea4314cf') of install.py is static and will not be altered while installation?

Sorry again for these stupid questions, this is my first pi project sophisticated to setting up a webserver or php and mysql - still learning

**Comment by danslimmon** [comment]
If you look at the full line with the URL, you'll see the `.format()` call following the string. That will use Python's [str.format](https://docs.python.org/2/library/stdtypes.html#str.format) method to interpolate the `{0}` with the desired value. In this case, trello_app_key.

Yeah, trello_app_key will stay the same as install.py runs. It corresponds to the Oscar Trello app, rather than your particular device. Hope that helps.
